const root=document.querySelector('[data-carousel]');const rail=root.querySelector('[data-rail]');const prev=root.querySelector('[data-prev]');const next=root.querySelector('[data-next]');const position=root.querySelector('[data-position]');let items=[];
async function load(){const r=await fetch('./content-rail.json',{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));return r.json()}
function card(item,index){return `<li class="card" data-card><picture class="card__media"><source type="image/avif" srcset="../assets/generated/${item.image}-640.avif 640w, ../assets/generated/${item.image}-${item.width}.avif ${item.width}w" sizes="(max-width:640px) 80vw,360px"><source type="image/webp" srcset="../assets/generated/${item.image}-640.webp 640w, ../assets/generated/${item.image}-${item.width}.webp ${item.width}w" sizes="(max-width:640px) 80vw,360px"><img src="../assets/generated/${item.image}-640.webp" alt="" ${index?'loading="lazy"':''}></picture><div class="card__body"><p class="eyebrow">${item.eyebrow}</p><h2>${item.title}</h2><p>${item.body}</p></div></li>`}
function render(data){items=data.carousel.items;rail.innerHTML=items.map(card).join('');requestAnimationFrame(update)}
function step(direction){const first=rail.querySelector('[data-card]');if(!first)return;const amount=first.getBoundingClientRect().width+parseFloat(getComputedStyle(rail).columnGap||16);rail.scrollBy({left:direction*amount,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
function update(){const cards=[...rail.querySelectorAll('[data-card]')];if(!cards.length)return;const left=rail.scrollLeft;const right=left+rail.clientWidth;let first=-1,last=0;cards.forEach((c,i)=>{const center=c.offsetLeft+c.offsetWidth*.5;if(first===-1&&center>=left)first=i;if(center<=right)last=i});if(first===-1)first=last;first=Math.min(first,last);position.textContent=`${first+1}–${last+1} von ${cards.length}`;prev.disabled=rail.scrollLeft<2;next.disabled=rail.scrollLeft+rail.clientWidth>=rail.scrollWidth-2;report()}
prev.addEventListener('click',()=>step(-1));next.addEventListener('click',()=>step(1));rail.addEventListener('scroll',()=>requestAnimationFrame(update),{passive:true});window.addEventListener('resize',update);
function report(){requestAnimationFrame(()=>window.parent.postMessage({type:'how-to-web:example-height',height:document.documentElement.scrollHeight},'*'))}
load().then(render).catch(e=>{console.warn('JSON konnte nicht geladen werden. Statischer Fallback bleibt aktiv.',e);items=[...rail.children];update()});
